### ISSUE TITLE
Example Program Crashes

### ISSUE THREAD

**Issue by ghost** [erincandescent/elfload#4]
Maybe I'm not understanding this correctly, but the program crashes whenever I try to load an ELF file that is not `sample.c`.

I've tried this code:

```
#include <stdio.h>
int main(void) {
  printf("Hello, world!\n");
  return 0;
}
```

Compiled it like so:

```
gcc main.c -fPIE -static -o main
```

And tried to run it:

```
elfloader ./main
```

And it crashes.

I confirmed that there is no shared library linkage with `ldd`.

I ran this on `x86_64` Linux.

**Comment by sam-truscott** [comment]
If it helps I've integrated this library into my bare metal Microkernel (https://github.com/sam-truscott/tinker-kernel). I use it to load user space applications into the kernel.

Can't remember what changes I made but it was mostly to support my Kernel's limitations (i.e. no stdio or libc of any kind).

It's a gradle build and the separate library is here: https://github.com/sam-truscott/tinker-kernel/tree/feature/newlib/libelf

I use it in the loader which is here: https://github.com/sam-truscott/tinker-kernel/blob/feature/newlib/kernel/src/kernel/c/loader/loader.c

**Comment by erincandescent** [comment]
Hi,

This is presumably statically linking glibc. elfload isn't passing the correct parameters to glibc's entry point - the linux kernel passes various parameters including the address of the aux vector. Additionally, I expect glibc requires some advanced elf features not supported by elfload. 

You'll note the sample function calls back out using a function pointer passed by the loader.

The sample program is to demonstrate how to load an ELF - it doesn't support loading ELF files for any particular OS; the sample file has to be compiled specially.

**Comment by ghost** [comment]
Gotcha. I was unaware of any parameters being passed to the entry point. Thanks for clearing that up for me.
